# permissions for end users to view observabilities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-viewer-role
rules:
- apiGroups:
  - observability.redhat.com
  resources:
  - observabilities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.redhat.com
  resources:
  - observabilities/status
  verbs:
  - get
