---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-operator
  namespace: kafka-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-operator
rules:
  - apiGroups:
      - "config.openshift.io"
    resources:
      - "clusterversions"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "networkpolicies"
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - "security.openshift.io"
    resources:
      - "securitycontextconstraints"
    resourceNames:
      - "privileged"
    verbs:
      - "use"
  - apiGroups:
      - "integreatly.org"
    resources:
      - grafanas
      - grafanadashboards
      - grafanadatasources
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
  - apiGroups:
      - "route.openshift.io"
    resources:
      - routes
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
  - apiGroups:
      - "authorization.k8s.io"
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - "authentication.k8s.io"
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - update
      - create
      - delete
      - watch
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "daemonsets"
      - "statefulsets"
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
  - apiGroups:
      - "operators.coreos.com"
    resources:
      - "subscriptions"
      - "operatorgroups"
      - "clusterserviceversions"
      - "catalogsources"
    verbs:
      - get
      - list
      - create
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
      - nodes/proxy
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
      - configmaps
      - endpoints
      - services
    verbs:
      - list
      - get
      - create
      - update
      - delete
      - watch
  - apiGroups:
      - corev1
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - prometheuses/finalizers
      - alertmanagers/finalizers
      - servicemonitors
      - podmonitors
      - prometheusrules
      - thanosrulers
      - thanosrulers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - observability.redhat.com
    resources:
      - observabilities
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - observability.redhat.com
    resources:
      - observabilities/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observability-operator
subjects:
  - kind: ServiceAccount
    name: observability-operator
    namespace: kafka-observability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-operator
  namespace: kafka-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      name: observability-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: observability-operator
    spec:
      serviceAccountName: observability-operator
      containers:
        - name: observability-operator
          image: quay.io/integreatly/observability-operator:latest
          ports:
            - containerPort: 60000
              name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "observability-operator"
---
